pipeline:
  drone_s3_cache_pull:
     image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
     drone_s3_cache_mode: "pull"

  build:
    commands:
       - "/root/entrypoint.sh 'sbt clean assembly'"
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.2.1
    when:
      event:
        - push
        - pull_request

  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
    drone_s3_cache_folders:
      - .ivy2
    drone_s3_cache_mode: "push"

  docker-build:
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t mercury .
    when:
      event: push

  integration:
    image: docker/compose:1.10.1
    privileged: true
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker-compose up -d
      - sleep 10
      - docker-compose exec -T mercury sbt it:test
      - docker-compose stop
      - sleep 10
      - docker-compose kill
    when:
      event: push

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
