version: "3"

services:
  sqs:
    image: kcomlabs/elasticmq
    ports:
      - 9324:9324

  s3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569

  hocs:
    image: davidainslie/hocs-fake
    ports:
      - 9000:9000

  mercury:
    build:
      context: .
      dockerfile: ./Dockerfile.integration

    environment:
      WEB_SERVICES_HOCS_URI: http://hocs:9000

    depends_on:
      - sqs
      - s3
      - hocs

    command: bash -c "sleep 3600"