apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: mercury

spec:
  replicas: 1

  template:
    metadata:
      labels:
        name: mercury

    spec:
      containers:
      - name: mercury
        image: mercury:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9100