apiVersion: v1
kind: Service

metadata:
  labels:
    name: mercury-service

  name: mercury-service

spec:
  ports:
  - name: exposed-port
    port: 9100
    targetPort: 9100

  selector:
    name: mercury