apiVersion: v1
kind: Service

metadata:
  labels:
    name: mercury-service

  name: mercury-service

spec:
  ports:
  - name: exposed-port
    port: 443
    targetPort: 443

  selector:
    name: mercury